@startuml



title Trust Over IP Trust Registry Protocol v2 Early Exploration

package EGF {

}



' object Error 
class TrustRegistry {
    EGFURI
    Entity(VID):   Entity
    Registry(VID): Registry
    Resource(VID): Resource
    Registries():  RegistryList
    Resources():   ResourceList
    RegistryMetadata: Metadata
    Lookups()
    OfflineCopy()
}

' class RegistryOfRegistries {
'     FindDID()
'     FindRegistry()
'     ListRegistries()


' }


class Lookup {
    Namespaces()
    VIDTypes() 
    Authorizations()
    ' ResourceTypes()
    ' CredentialTypes()
    ' CredentialSchemas()
    ' PresentationRequests()
    ' Overlays()
    AssuranceLevels()
     
}

class Metadata {
    EGFURI: URI ' (duplicated above)
    TrustRegistryName: string
    RawAPIEndpoint: URL 
    ' AuthorityClaim: string 
    lastUpdated: datetime 
    namespaces: string[]
    

    ' Languages() 
}

' inheritance
EGF "1" -- "1" TrustRegistry


TrustRegistry <|-- Lookup 

package QueryDataObjects {
    
    class RegistryList
    class ResourceList
    class EntityList

    class Entity {
        identifier: VID
        didmethod: DIDMethod
        Authorizations[]
        registryListings[]
        Namespaces[]
        HasAuthorization(Authorization)
    }

    object Registry {
        identifier: VID
        name: string
        peerType: enum
        description: string
        RecognizedNamespaces[]
    }
    object Resource {
        identifier: VID 
        lastUpdated: datetime
        datatype: string
        payloadJSON: JSON
        payloadURI: string
        integrity: Integrity
    }
}

object Integrity

package Lookups {
    package LookupLists {
        object NamespaceList
        object VIDTypeList
        object AssuranceLevelList
        object AuthorizationList      
    }

    object VIDType {
        VIDtype: string 
        maximumAssuranceLevel: AssuranceLevel
    }

    object Authorization {
        authorization: string 
    }

  
    object Namespace
    object AssuranceLevel {
        identifier: string
        name: string
        'TODO multilingual
    }


}


class ExportFile {
    Lookups.AssuranceLevels
    Lookups.VIDTypes
    Lookups.Authorizations
    Lookups.Namepaces 
    Entities: EntityList
    Registries: RegistryList
    Resources: ResourceList 
    Metadata 
    Validity


}

Class ValidityDatesType {
    validFromDT: datetime
    validtoDT: datetime
}

EntityList o-- "0..n" Entity
RegistryList  o-- "0..n" Registry
ResourceList  o-- "0..n" Resource 

Resource::integrity --> Integrity

Lookup::VIDTypes --> VIDTypeList
Lookup::Authorizations --> AuthorizationList
Lookup::AssuranceLevels --> AssuranceLevelList
Lookup::Namespaces --> NamespaceList

' METADATA related objects
TrustRegistry --> Metadata 
TrustRegistry::Entity --> Entity 
TrustRegistry::Registry --> Registry
TrustRegistry::Resource --> Resource
TrustRegistry::Registries --> RegistryList 
TrustRegistry::Resources --> ResourceList

' ExportFile::Validity --> ValidityDatesType

VIDTypeList o-- "1...n" VIDType 
AuthorizationList o-- "0...n" Authorization
NamespaceList o-- "0..n" Namespace



'' EXPORT FILE
TrustRegistry::OfflineCopy --> ExportFile



AssuranceLevelList o-- "0...n" AssuranceLevel


@enduml