@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml


title Native and Bridged Support for TRQP - Implementer Review Draft

Person(Integrator, "Integrator", "Ecosystem Developer")

System(Bridge, "Generic Bridge")
System(teBridge, "DIF \n Credential Trust Establishment \nBridge","[CTE]")

System(oidcBridge, "OIDF Bridge")
System(oidfData,"Federation","OIDF\nProfile 1")
System(oidfDataN,"Federation","OIDF\nProfile N")
Rel(Integrator, oidcBridge,"TRQP")
Rel(oidcBridge,oidfData,"OIDF\nProfile 1")
Rel(oidcBridge,oidfDataN,"OIDF\nProfile N")

System(TRAIN, "TRAIN") 
Rel(Bridge, TRAIN,"bridges")



System(EUTrustedList, "EU Trusted List")
System(NativeSupport, "SystemX"," w Native TRQP Support")



System(teFile, "CTE file")

Rel(teBridge, teFile,"processes")

Rel(Integrator, Bridge, "TRQP")
Rel(Integrator, teBridge, "TRQP")


Rel(Bridge, EUTrustedList, "bridges")


' System(OpenDataBridge, "OpenData Bridge")
' Rel(Integrator, OpenDataBridge,"TRQP")
' Rel(OpenDataBridge,NativeSupport,"ODPS")

Rel(Integrator, NativeSupport,"TRQP")



@enduml 