@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml


title Native and Bridged Support for TRP - Implementer Review Draft

Person(Integrator, "Integrator", "Ecosystem Developer")

System(Bridge, "Generic Bridge")
System(teBridge, "DIF \n Credential Trust Establishment \nBridge","[CTE]")

System(oidcBridge, "OIDF Bridge")
System(oidfData,"Federation","OIDF")

Rel(Integrator, oidcBridge,"TRP")
Rel(oidcBridge,oidfData,"OIDF")


System(TRAIN, "TRAIN") 
Rel(Bridge, TRAIN,"bridges")



System(EUTrustedList, "EU Trusted List")
System(NativeSupport, "SystemX"," w Native TRP Support")



System(teFile, "CTE file")

Rel(teBridge, teFile,"processes")

Rel(Integrator, Bridge, "TRP")
Rel(Integrator, teBridge, "TRP")


Rel(Bridge, EUTrustedList, "bridges")


' System(OpenDataBridge, "OpenData Bridge")
' Rel(Integrator, OpenDataBridge,"TRP")
' Rel(OpenDataBridge,NativeSupport,"ODPS")

Rel(Integrator, NativeSupport,"TRP")



@enduml 